# Generated by Django 2.2.10 on 2020-03-01 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_auto_20200229_1217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nombre'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Producutos'},
        ),
    ]
