# Generated by Django 2.2.10 on 2020-03-02 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_auto_20200302_1438'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
