# Generated by Django 2.2.10 on 2020-02-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('asunto', models.CharField(max_length=70)),
                ('mensaje', models.TextField()),
                ('respondido', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now=True)),
                ('modificado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'contacto',
                'ordering': ['-creado'],
            },
        ),
    ]
