# Generated by Django 2.2.10 on 2020-02-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='carrusel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='imagenes/carrusel/')),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Carrusel',
                'verbose_name_plural': 'Carruseles',
                'db_table': 'carrusel',
                'ordering': ['creado'],
            },
        ),
    ]
