# Generated by Django 2.2.10 on 2020-02-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0003_remove_carrusel_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrusel',
            name='img',
            field=models.ImageField(default='algo', upload_to='imagenes/carrusel/'),
        ),
    ]
