# Generated by Django 2.2.10 on 2020-03-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0005_auto_20200227_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bancos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='imagenes/bancos/')),
                ('banco', models.CharField(max_length=100)),
                ('cuenta', models.CharField(max_length=20)),
                ('tipo', models.CharField(blank=True, choices=[('', ''), ('corriente', 'Corriente'), ('ahorro', 'Ahorro')], max_length=9, null=True)),
                ('nombre', models.CharField(max_length=75)),
                ('cedula', models.CharField(max_length=10)),
                ('estado', models.BooleanField(default=0)),
            ],
        ),
    ]
