# Generated by Django 2.2.10 on 2020-03-07 20:07

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0007_auto_20200307_1317'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bancos',
            managers=[
                ('banco_activo', django.db.models.manager.Manager()),
            ],
        ),
    ]
