# Generated by Django 2.2.10 on 2020-03-07 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0008_auto_20200307_1607'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bancos',
            managers=[
            ],
        ),
    ]
