# Generated by Django 2.2.10 on 2020-03-09 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sitio', '0009_auto_20200307_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModoPago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'ModoPago',
                'db_table': 'modo_pago',
                'verbose_name_plural': 'ModolPagos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_pago', models.IntegerField(unique=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('modo_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitio.ModoPago')),
            ],
        ),
    ]
