# Generated by Django 2.2.10 on 2020-03-09 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sitio', '0010_modopago_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='modopago',
            name='creado_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modopago',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
